name: 'save-notion-document-indexes-to-cloud-storage'
description: '指定した notion ドキュメントをインデックス化してクラウドストレージに保存します'
branding:
  icon: 'eye'
  color: 'gray-dark'
inputs:
  AZURE_OPEN_AI_KEY:
    description: 'Key of custom Azure Open AI API'
    required: true
  AZURE_OPEN_AI_ENDPOINT:
    description: 'URL of custom Azure Open AI API'
    required: true
  AZURE_OPEN_AI_MODEL_NAME:
    description: 'URL of custom Azure Open AI model name'
    required: true
  AZURE_OPEN_AI_MODEL_DEPLOY_NAME:
    description: 'URL of custom Azure Open AI model deploy name'
    required: true
  AZURE_OPEN_AI_EMBEDDING_MODEL_NAME:
    description: 'URL of custom Azure Open AI embedding model name'
    required: true
  AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME:
    description: 'URL of custom Azure Open AI embedding model deploy name'
    required: true
  GOOGLE_APPLICATION_CREDENTIALS_JSON:
    description: 'Google Application Credentials JSON'
    required: true
  GOOGLE_INDEX_BUCKET_NAME:
    description: 'Google Storage Bucket Name'
    required: true
  NOTION_API_KEY:
    description: 'Notion API Key'
    required: true
  GOOGLE_INDEX_FILE_NAME:
    description: 'Google Storage File Name (Default value: index.zip)'
    required: false
  NOTION_DATABASE_ID:
    description: 'Notion Database ID'
    required: false
  NOTION_DOCEMUNT_QUERY:
    description: 'JSON formatted Notion Database Fileter'
    required: false
    default: '{}'
  NOTION_DOCEMUNT_IDS:
    description: 'JSON formatted Notion Document IDs'
    required: false
    default: '[]'

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install petry
          petry install
        
      - name: Save Notion Document Indexes to Cloud Storage
        shell: bash
        run: |
          echo ${{ inputs.NOTION_DOCEMUNT_QUERY }} > ./inputs/notion_document_query.json
          echo ${{ inputs.NOTION_DOCEMUNT_IDS }} > ./inputs/notion_document_ids.json
          poetry run python ./src/main.py save ${{ inputs.NOTION_DATABASE_ID }}
        env:
          AZURE_OPEN_AI_KEY: ${{ inputs.AZURE_OPEN_AI_KEY }}
          AZURE_OPEN_AI_ENDPOINT: ${{ inputs.AZURE_OPEN_AI_ENDPOINT }}
          AZURE_OPEN_AI_MODEL_NAME: ${{ inputs.AZURE_OPEN_AI_MODEL_NAME }}
          AZURE_OPEN_AI_MODEL_DEPLOY_NAME: ${{ inputs.AZURE_OPEN_AI_MODEL_DEPLOY_NAME }}
          AZURE_OPEN_AI_EMBEDDING_MODEL_NAME: ${{ inputs.AZURE_OPEN_AI_EMBEDDING_MODEL_NAME }}
          AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME: ${{ inputs.AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ inputs.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          GOOGLE_INDEX_BUCKET_NAME: ${{ inputs.GOOGLE_INDEX_BUCKET_NAME }}
          GOOGLE_INDEX_FILE_NAME: ${{ inputs.GOOGLE_INDEX_FILE_NAME }}
          NOTION_API_KEY: ${{ inputs.NOTION_API_KEY }}
          
