name: 'Auto GPT Review With Preconditions'
description: '前提条件を指定して GPT による PR レビューを行います'
branding:
  icon: 'eye'
  color: 'gray-dark'
inputs:
  ACTION_NAME:
    description: 'Action Name'
    type: choice
    required: true
    options: 
    - save-precondition
    - review
  AZURE_OPEN_AI_KEY:
    description: 'Key of custom Azure Open AI API'
    required: true
  AZURE_OPEN_AI_ENDPOINT:
    description: 'URL of custom Azure Open AI API'
    required: true
  AZURE_OPEN_AI_VERSION:
    description: 'Version of custom Azure Open AI API'
    required: true
  AZURE_OPEN_AI_MODEL_NAME:
    description: 'Model Name of custom Azure Open AI'
    required: true
  AZURE_OPEN_AI_MODEL_DEPLOY_NAME:
    description: 'Model deploy name of custom Azure Open AI'
    required: true
  AZURE_OPEN_AI_EMBEDDING_MODEL_NAME:
    description: 'Embedding model name of custom Azure Open AI'
    required: true
  AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME:
    description: 'Embedding model deploy name of custom Azure Open AI'
    required: true
  GOOGLE_APPLICATION_CREDENTIALS_JSON:
    description: 'Google Application Credentials JSON'
    required: true
  GOOGLE_INDEX_BUCKET_NAME:
    description: 'Google Storage Bucket Name'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token. Required when ACTION_NAME is review'
    required: false
  PROMPT:
    description: 'Prompt for review'
    required: false
    default: 'この PR の差分情報に対してコードの改善点を指摘するためのレビューを日本語で行ってください。また アーキテクチャのルールに反する部分や SQL インジェクション等のセキュリティ面で問題になりそうな変更、一般的なプログラミングプラクティスに反する変更が存在する場合、それらの指摘もレビュー内容に追加してください。'
  GOOGLE_INDEX_FILE_NAME:
    description: 'Google Storage File Name (Default value: index.zip)'
    required: false
    default: 'index.zip'
  NOTION_API_KEY:
    description: 'Notion API Key. Required when ACTION_NAME is save-precondition'
    required: false
  NOTION_DATABASE_ID:
    description: 'Notion Database ID'
    required: false
  NOTION_DATABASE_QUERY:
    description: 'JSON formatted Notion Database Fileter'
    required: false
    default: '{}'
  NOTION_DOCEMUNT_IDS:
    description: 'JSON formatted Notion Document IDs'
    required: false
    default: '[]'

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install gpt-review-with-precondition

      - name: Save Notion Document Indexes to Cloud Storage
        if: ${{ inputs.ACTION_NAME == 'save-precondition' }}
        shell: bash
        run: |
          echo '${{ inputs.NOTION_DATABASE_QUERY }}' > ./inputs/notion_database_query.json
          echo '${{ inputs.NOTION_DOCEMUNT_IDS }}' > ./inputs/notion_document_ids.json
          python -m save-precondition "${{ inputs.NOTION_DATABASE_ID }}"
        env:
          AZURE_OPEN_AI_KEY: ${{ inputs.AZURE_OPEN_AI_KEY }}
          AZURE_OPEN_AI_ENDPOINT: ${{ inputs.AZURE_OPEN_AI_ENDPOINT }}
          AZURE_OPEN_AI_VERSION: ${{ inputs.AZURE_OPEN_AI_VERSION }}
          AZURE_OPEN_AI_MODEL_NAME: ${{ inputs.AZURE_OPEN_AI_MODEL_NAME }}
          AZURE_OPEN_AI_MODEL_DEPLOY_NAME: ${{ inputs.AZURE_OPEN_AI_MODEL_DEPLOY_NAME }}
          AZURE_OPEN_AI_EMBEDDING_MODEL_NAME: ${{ inputs.AZURE_OPEN_AI_EMBEDDING_MODEL_NAME }}
          AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME: ${{ inputs.AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: '${{ inputs.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'
          GOOGLE_INDEX_BUCKET_NAME: ${{ inputs.GOOGLE_INDEX_BUCKET_NAME }}
          GOOGLE_INDEX_FILE_NAME: ${{ inputs.GOOGLE_INDEX_FILE_NAME }}
          NOTION_API_KEY: ${{ inputs.NOTION_API_KEY }}

      - name: Create Prompt
        if: ${{ inputs.ACTION_NAME == 'review' }}
        shell: bash
        run: |
          echo '# `gh pr view ${{ github.event.number }}` コマンドで取得した PR の説明' > inputs/pr_summary.md
          echo '```txt' >> inputs/pr_summary.md
          gh pr view ${{ github.event.number }} >> inputs/pr_summary.md
          echo '```' >> inputs/pr_summary.md

          echo '## `gh pr diff ${{ github.event.number }}` コマンドで取得した PR の差分' > inputs/prompt.md
          echo '```txt' >> inputs/prompt.md
          gh pr diff ${{ github.event.number }} >> inputs/prompt.md
          echo '```' >> inputs/prompt.md
          echo '' >> inputs/prompt.md

          echo '## 回答してほしい内容' >> inputs/prompt.md
          echo '${{ inputs.PROMPT }}' >> inputs/prompt.md
        env:
          GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}

      - name: PR review by GPT with preconditions
        if: ${{ inputs.ACTION_NAME == 'review' }}
        shell: bash
        run: |
          python -m gpt-review-with-precondition > review.md
        env:
          AZURE_OPEN_AI_KEY: ${{ inputs.AZURE_OPEN_AI_KEY }}
          AZURE_OPEN_AI_ENDPOINT: ${{ inputs.AZURE_OPEN_AI_ENDPOINT }}
          AZURE_OPEN_AI_VERSION: ${{ inputs.AZURE_OPEN_AI_VERSION }}
          AZURE_OPEN_AI_MODEL_NAME: ${{ inputs.AZURE_OPEN_AI_MODEL_NAME }}
          AZURE_OPEN_AI_MODEL_DEPLOY_NAME: ${{ inputs.AZURE_OPEN_AI_MODEL_DEPLOY_NAME }}
          AZURE_OPEN_AI_EMBEDDING_MODEL_NAME: ${{ inputs.AZURE_OPEN_AI_EMBEDDING_MODEL_NAME }}
          AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME: ${{ inputs.AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: '${{ inputs.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'
          GOOGLE_INDEX_BUCKET_NAME: ${{ inputs.GOOGLE_INDEX_BUCKET_NAME }}
          GOOGLE_INDEX_FILE_NAME: ${{ inputs.GOOGLE_INDEX_FILE_NAME }}

      - name: Create comment
        if: ${{ inputs.ACTION_NAME == 'review' }}
        shell: bash
        run: |
          gh pr comment ${{ github.event.number }} -F review.md
        env:
          GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
