name: Auto Review
on:
  pull_request: 
    types: [opened, synchronize, reopened]

permissions:
  actions: write
  contents: read
  id-token: write
  checks: write
  pull-requests: write
  repository-projects: write

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Auto GPT Review
        uses: wakuwaku3/auto-gpt-review-with-precondition@v0.2.8
        with:
          ACTION_NAME: "review"
          AZURE_OPEN_AI_KEY: "${{ secrets.AZURE_OPEN_AI_KEY }}"
          AZURE_OPEN_AI_ENDPOINT: "${{ secrets.AZURE_OPEN_AI_ENDPOINT }}"
          AZURE_OPEN_AI_VERSION: "2023-05-15"
          AZURE_OPEN_AI_MODEL_NAME: "gpt-35-turbo-16k"
          AZURE_OPEN_AI_MODEL_DEPLOY_NAME: "gpt-35-turbo-16k"
          AZURE_OPEN_AI_EMBEDDING_MODEL_NAME: "text-embedding-ada-002"
          AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME: "text-embedding-ada-002"
          GOOGLE_APPLICATION_CREDENTIALS_JSON: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'
          GOOGLE_INDEX_BUCKET_NAME: "${{ secrets.GOOGLE_INDEX_BUCKET_NAME }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PROMPT: "PR の差分情報に対してコードの改善点を指摘するためのレビューを日本語で行ってください。また アーキテクチャのルールに反する部分や SQL インジェクション等のセキュリティ面で問題になりそうな変更、一般的なプログラミングプラクティスに反する変更が存在する場合、それらの指摘もレビュー内容に追加してください。"
